spring.application.name=scms
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost;databaseName=scms;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Welcome@1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
